
# Since this is a pure static site, no build command is needed.
[build]
  publish = "/"

# SPA-style fallback so pretty URLs work even if navigated directly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
